sudo: required
language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
matrix:
  fast_finish: true
  include:
    - os: linux
      env: OCAML_VERSION=4.03 OPAM_VERSION=1.2.2 TEST=parsing
    - os: linux
      env: OCAML_VERSION=4.03 OPAM_VERSION=1.2.2 TEST=round
    - os: linux
      env: OCAML_VERSION=4.03 OPAM_VERSION=1.2.2 TEST=mergeA
    - os: linux
      env: OCAML_VERSION=4.03 OPAM_VERSION=1.2.2 TEST=mergeB
    - os: linux
      env: OCAML_VERSION=4.03 OPAM_VERSION=1.2.2 TEST=mergeC

    # At the moment bootstrapping OCaml on OSX takes too long, for the sake of
    # simplicity just test compilation
    - os: osx
      env: OCAML_VERSION=4.03 OPAM_VERSION=1.2.2

script:
  - bash -ex .travis-ocaml.sh
  - bash -ex ./tools/travis_ci_test.sh
